---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-carts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: retail-store-app-charts/cart/chart
    helm:
      values: |
        mysql:
          enabled: false
        postgresql:
          enabled: false
        dynamodb:
          enabled: false
        replicaCount: 2
        datasource:
          url: "jdbc:mysql://carts-db:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-catalog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: retail-store-app-charts/catalog/chart
    helm:
      values: |
        mysql:
          enabled: false
        postgresql:
          enabled: false
        dynamodb:
          enabled: false
        replicaCount: 2
        datasource:
          url: "jdbc:mysql://catalog-db:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-orders
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: retail-store-app-charts/orders/chart
    helm:
      values: |
        mysql:
          enabled: false
        postgresql:
          enabled: false
        dynamodb:
          enabled: false
        replicaCount: 2
        datasource:
          url: "jdbc:mysql://orders-db:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-checkout
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: retail-store-app-charts/checkout/chart
    helm:
      values: |
        mysql:
          enabled: false
        postgresql:
          enabled: false
        dynamodb:
          enabled: false
        replicaCount: 2
        checkout:
          dynamodb:
            tableName: "project-bedrock-retail-store"
            region: "us-east-1"
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: retail-store-app-charts/ui/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: kubernetes/retail-store
    directory:
      include: 'rabbitmq.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: kubernetes/retail-store
    directory:
      include: 'redis.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: kubernetes/retail-store/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ingressclass
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Tbraima44/PROJECT-BEDROCK-ARGOCD.git
    targetRevision: main
    path: kubernetes/retail-store/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true