# Disable all in-cluster databases
mysql:
  enabled: false
postgresql:
  enabled: false
dynamodb:
  enabled: false

# Number of replicas
replicaCount: 1

# Cart Service
carts:
  datasource:
    url: "jdbc:mysql://project-bedrock-mysql.cajmqcu2syh5.us-east-1.rds.amazonaws.com:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true"
    username: "admin"
    password: "YourSecurePassword123!"

# Catalog Service
catalog:
  datasource:
    url: "jdbc:mysql://project-bedrock-mysql.cajmqcu2syh5.us-east-1.rds.amazonaws.com:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true"
    username: "admin"
    password: "YourSecurePassword123!"

# Orders Service
orders:
  datasource:
    url: "jdbc:mysql://project-bedrock-mysql.cajmqcu2syh5.us-east-1.rds.amazonaws.com:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true"
    username: "admin"
    password: "YourSecurePassword123!"

# Checkout Service
checkout:
  dynamodb:
    tableName: "project-bedrock-retail-store"
    region: "us-east-1"