mysql:
  enabled: false
postgresql:
  enabled: false
dynamodb:
  enabled: false

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

datasource:
  url: "jdbc:mysql://carts-db:3306/retaildb?useSSL=false&allowPublicKeyRetrieval=true"